### ISSUE TITLE
[homescreen]: add/remove widgets in top section

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#100]

**Comment by notmart** [comment]
a very basic applet add/remove/move is in plasma-phone-components
will need a lot more work, but should be enough to try out plasmoids in the homescreen

**Comment by jriddell** [comment]
plasma-phone-components is built in on-demand 22-Jun-2015 23:48 UTC

**Comment by star-buck** [comment]
@notmart : how to trigger the mode to add widgets?

**Comment by notmart** [comment]
long press anywhere, in empty areas or on top of the widgets pops up a menu with action to change the wallpaper or add widgets. after long press is also possible to drag them around to reorder them
