### ISSUE TITLE
[energy kcm]: ui needs adjustments to fit for mobile

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#139]

**Comment by sebasje** [comment]
Fixed with http://commits.kde.org/kinfocenter/19f21cfcea293b2fed599ebcf4b5f374136861cd

**Comment by star-buck** [comment]
is that packaged yet and shipped with an IMG?
if not, lets leave the ticket open to remind packaging and close it when actually confirmed working on an IMG.

**Comment by sebasje** [comment]
I've updated the package, but it's not on an image yet.

**Comment by jriddell** [comment]
on image 130
