### ISSUE TITLE
[taskswitcher]

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/mobster#149]
The taskswitcher passes incorrect row numbers to PlasmaWindowModel for requestActivate and requestClose.

The problem is that in Task.qml we have e.g.:
plasmoid.nativeInterface.windowModel.requestClose(model.index)

The index, though, is not for the windowModel, but for a FilterProxyModel defined in TaskSwitcher.qml:
PlasmaCore.SortFilterModel {
            id: filteredWindowModel
            filterRole: "DisplayRole"
            filterRegExp: ".+"
            sourceModel: plasmoid.nativeInterface.windowModel
        }

If I remove filterRole and filterRegExp (that is the index of filter model applies to windowModel, too) switching tasks and closing tasks start to work.

**Comment by eikehein** [comment]
Fixed in 12ba70727.
