### ISSUE TITLE
kci plasma-phone-meta

### ISSUE THREAD

**Issue by jriddell** [blue-systems/mobster#152]
plasma-phone-meta is the lovely new meta package to replace the long list in chroot-remaster, I've uploaded it using on demand but please add it to mobile.kci
    "plasma-phone-meta":
        ["git@github.com:plasma-mobile/plasma-phone-meta.git",
        "git@github.com:plasma-phone-packaging/plasma-phone-meta.git",
        "kubuntu_unstable"]

**Comment by jriddell** [comment]
needs germinate installed on whatever builds the source packages
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_plasma-phone-meta_src/lastFailedBuild/console

**Comment by apachelogger** [comment]
why are we using germinate?

**Comment by jriddell** [comment]
cos that's how seeds get turned into meta packages?

**Comment by apachelogger** [comment]
but why are we using a seed? this seems vastly overengineered for what we are doing with it

**Comment by jriddell** [comment]
cos a seed file is tidier than a long list of dependencies or a bash script

the problem is I couldn't work out how to get germinate to use git, it'll try but it won't add the .git on the end of the url so I had to use bzr on launchpad

**Comment by apachelogger** [comment]
...overnegineering

http://manpages.ubuntu.com/manpages/precise/man5/deb-substvars.5.html

**Comment by jriddell** [comment]
like the Forth Bridge it'll be a world heritage site one day

**Comment by apachelogger** [comment]
as of http://mobile.kci.pangea.pub:8080/job/mgmt_docker_vivid/24/ the tooling should install germinate to generate sources
