### ISSUE TITLE
Please package libkgapi/frameworks and kcontacts/master

### ISSUE THREAD

**Issue by mck182** [blue-systems/mobster#154]
These are now dependencies of plasma-settings

There's also newly libaccounts-qt5, signon-qt5 and libkaccounts dependency on plasma-settings.

**Comment by apachelogger** [comment]
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_kcontacts_src/
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_kcalcore_src/
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_libkgapi_src/

dep adjustment over in #155
