### ISSUE TITLE
Add new dependencies to plasma-settings

### ISSUE THREAD

**Issue by mck182** [blue-systems/mobster#155]
On Harald's request, a new issue.

New required build deps for plasma-settings
 * ~~libaccounts-qt5~~
 * ~~libsignon-qt5~~
 * ~~libkaccounts~~
 * ~~libkgapi/frameworks~~
 * ~~kcontacts~~

Runtime deps
 * ~~kaccounts-integration~~
 * ~~kaccounts-providers~~
 * signon-ui (the patched version from #153)
 * signond

**Comment by apachelogger** [comment]
buil depends adjusted, signon stuff waiting for signon-ui patchery

**Comment by mck182** [comment]
Turns out plasma-settings will require KF5CalendarCore as a build dependency too; it's a find_dependency of kgapi.

http://mobile.kci.pangea.pub:8080/job/vivid_unstable_plasma-settings-packaging_bin_amd64/18/console

**Comment by apachelogger** [comment]
thought I did that

**Comment by apachelogger** [comment]
ah, settings wasn't triggered with the fix. triggered it. should be fixed now

**Comment by apachelogger** [comment]
as it turns out reading helps and this is really #158 as the package is there the versions just dont match

**Comment by apachelogger** [comment]
Dependency wise this should be sorted as kaccounts-integraton drags in the relevant parts of the signon stack (among them "signon-ui-x11, signond")

**Comment by jriddell** [comment]
<mck182> sebas: yup, the module is now built only if kaccounts && libaccounts-qt5 && libsignon-qt5 && libkgapi && libkcontacts have been found
