### ISSUE TITLE
[packaging] Include 72aa34dc2aebbea715a5915f26cb6f0f67e164d1 to QtWayland package

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/mobster#157]
Please include commit 72aa34dc2aebbea715a5915f26cb6f0f67e164d1 in QtWayland [1]. This commit fixes the generation of the wl_shell_window_class which is required for getting window icons.

E.g. without the patch we get "konsole.desktop" which does not (!) match any installed desktop file. With the patch we get "org.kde.konsole" which we can map to an existing desktop file.

[1] http://quickgit.kde.org/?p=qt%2Fqtwayland.git&a=commit&h=72aa34dc2aebbea715a5915f26cb6f0f67e164d1

**Comment by apachelogger** [comment]
https://launchpad.net/~plasma-phone/+archive/ubuntu/ppa/+sourcepub/5216346/+listing-archive-extra
