### ISSUE TITLE
libkgapi wants kcalcore 4.88

### ISSUE THREAD

**Issue by apachelogger** [blue-systems/mobster#158]
libkgapi wants kcalcore 4.88 (KDEPIMLIBS_LIB_VERSION, used in the KF5GAPIConfig.cmake.in)

kcalcore's master however is at 4.81 (KCALENDARCORE_LIB_VERSION)

things that look for kgapi don't build -> http://mobile.kci.pangea.pub:8080/job/vivid_unstable_plasma-settings-packaging_bin_amd64/19/console

**Comment by apachelogger** [comment]
labeling high what with it braeking plasma-settings build :tongue:

**Comment by mck182** [comment]
Fix pushed in kgapi master. In other news, dvratil merged frameworks into master.
