### ISSUE TITLE
[packaging] CI-build of breeze (kwin style) needed

### ISSUE THREAD

**Issue by mgraesslin** [blue-systems/mobster#161]
We just noticed that KWin is crashing as soon as one opens a new Xwayland client. The problem is that KWin fails to load the breeze deco as the one in the archive is too old. Falls back to Aurorae which tries creating an OpenGL context in QtQuick, fails with that and QtQuick aborts.

**Comment by apachelogger** [comment]
building now http://mobile.kci.pangea.pub:8080/job/vivid_unstable_breeze_bin_armhf/1/console

unless the packaging is broken should be built within the hour

**Comment by apachelogger** [comment]
looking green
