### ISSUE TITLE
[packaging]: install kio package by default

### ISSUE THREAD

**Issue by notmart** [blue-systems/mobster#162]
provides file:/ trash:/ etc, necessary to have kioslaves working, fixes wallpaper previews in the selection dialog

**Comment by apachelogger** [comment]
chances are the fix for this actually wont build as we haven't updated our builds in more than a week due to semi-freeze status of the image

**Comment by apachelogger** [comment]
http://mobile.kci.pangea.pub:8080/job/vivid_unstable_plasma-workspace_bin_armhf/6/
