### ISSUE TITLE
[Packaging] Remove devel-proposed2 channel

### ISSUE THREAD

**Issue by bhush9** [blue-systems/mobster#178]
I am not sure from where this came but http://kubuntu.plasma-mobile.org/channels.json provides this channel,

```
"kubuntu-phone/devel-proposed2": {
        "devices": {
            "hammerhead": {
                "index": "/kubuntu-phone/devel-proposed2/hammerhead/index.json"
            }
        }
    }
```

And http://kubuntu.plasma-mobile.org/kubuntu-phone/devel-proposed2/hammerhead/index.json

gives 404.. This creates problems when using it with MultiROM manager and makes MultiROM manager crash

**Comment by jriddell** [comment]
not sure how that snuck back in there, gone now
