### ISSUE TITLE
network manager: says wifi connected, but actually isnt...(because of kwallet?)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#182]
only when using wifi-setup from adb shell, a connection gets established, despite kwallet popping up 3xtimes again while pressing "cancel"

**Comment by bhush9** [comment]
somehow NetworkManager is not setting up DNS. so if you don't use wifi-setup script it won't get DNS.. after connecting from NetworkManager it should write DNS settings to /etc/resolv.conf which it is not doing somehow. If reason for this is found wifi-setup script will no longer be needed..

I will investigate this..

**Comment by bhush9** [comment]
I've created patch... (I am not too sure about how Images are created)

@jriddell if you think this patch is feasible.. merge #184
