### ISSUE TITLE
[apps]: muon-discover

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#75]

**Comment by aleixpol** [comment]
Status update:
* Application starts but needs work to adapt to the form factor.
* QApt works, although the UI is widget-based and doesn't look very well.
* We need to investigate whether there's anything we can do about the PackageKit click backend, because it seems to work but not for some important actions
 * Listing and install-local works, install and remove doesn't
* We need to see what to do with the app-install desktop files, whether we can adapt it for phone. Or finally move to appstream for good.

**Comment by star-buck** [comment]
installing "muon" package currently still drags in lots of (qt4-)dependencies

**Comment by aleixpol** [comment]
We looked into it with @shadeslayer. It seems to be because of kdesudo (at least). This case is solved in master.

**Comment by star-buck** [comment]
@apachelogger : please package muon from master and include in next IMG

**Comment by star-buck** [comment]
needs additional package to work:
* app-install-data

**Comment by apachelogger** [comment]
@aleixpol which package do we want muon or muon-discover? (I presume latter)

**Comment by aleixpol** [comment]
@apachelogger muon-discover

**Comment by apachelogger** [comment]
built and add to mobster

@jriddell kindly note muon-discover on next image

**Comment by jriddell** [comment]
it's on.

**Comment by star-buck** [comment]
126: icon is there, but muon doesnt start

**Comment by star-buck** [comment]
still doesnt start in IMG 135.
Either remove the app completely or make it work until akademy.

**Comment by aleixpol** [comment]
It's a weird issue, if it's started from adb, it runs correctly, from plasma it doesn't start. Anybody knows how to debug it?

**Comment by star-buck** [comment]
maybe use konsole shipped on the IMG and start "muon-discover" from there?

**Comment by aleixpol** [comment]
I realized it's a small issue with Plasma QtQuick Controls, I'm trying to figure it out. Using Konsole was useful, thanks @star-buck :D

**Comment by aleixpol** [comment]
Should be fixed now, in master. I'm seeing different visual issues as I'm testing it, will look into them, but it's ready for testing.

**Comment by star-buck** [comment]
IMG 137: still doesnt start :/

**Comment by aleixpol** [comment]
Do we have an up to date plasma-framework?

**Comment by aleixpol** [comment]
Just looked into it, we need to get a fresh Muon Discover.

More precisely, we need 9352fbd124c0f1e082b1d39620d95d73d239215e from the 21st July, currently we have a version for the 17th July.

@apachelogger Can we maybe get Muon in the CI?

**Comment by apachelogger** [comment]
@aleixpol http://mobile.kci.pangea.pub:8080/job/vivid_unstable_muon_src/ ?

**Comment by jriddell** [comment]
new version building now
