### ISSUE TITLE
[volume buttons]: map volume buttons to OSD

### ISSUE THREAD

**Issue by star-buck** [blue-systems/mobster#96]
initial suggestion by mgraesslin:
* finish kglobalaccel port of Wayland (https://todo.kde.org/?controller=task&action=show&task_id=41 )
* ship kmix on the phone
* things start to work autmatically as kmix registers the global shortcuts

For the record: KWin already receives the volume key events. We can delegate them, but the only place I want them to be delegated to is kglobalaccel. Everything else means a phone-specific code path which later on needs to be removed again.

**Comment by mgraesslin** [comment]
suggestion: use normal architecture:
* port kglobalaccel to wayland as discussed
* use kmix
* use standard osd functionality of kmix<->plasmashell

**Comment by mck182** [comment]
@mgraesslin Sounds like a plan. Although KMix might be unnecessarily heavy. Maybe @apachelogger's new volume applet/its backend would be simpler to use?

Also, has any work on kglobalaccel/wayland started?

**Comment by mgraesslin** [comment]
> Also, has any work on kglobalaccel/wayland started?

kglobalaccel is split into plugins. But that's about it.

**Comment by mgraesslin** [comment]
some progress on the global accel part: frameworks and kwin reviews are prepared. Once the code gets in, it should magically start to work (assuming the volume applet grabs KMix's keys)

**Comment by mgraesslin** [comment]
kglobalaccel, kwin and simplelogin are adjusted. One of the next image should have volume buttons working if the applet has registered global shortcuts.

@apachelogger does your applet grab KMix's global shortcuts?

**Comment by apachelogger** [comment]
ENOTIMPLEMENTED

**Comment by star-buck** [comment]
On desktop side, installing kmix alongside new volume mixer allows for OSD to work.
On phone adding kmix does not seem to help.
So with kglobalaccel, kwin and simplelogin prepared, is it only registering the shortcuts thats missing?

**Comment by mgraesslin** [comment]
starting kmix should register the shortcuts. I can give it a try, to verify whether the shortcuts are installed and get triggered.

What is probably missing is the OSD in plasma-phone.

**Comment by mgraesslin** [comment]
I have now tried it on the exopc and there starting kmix makes the normal volume keys work and also an OSD show

**Comment by apachelogger** [comment]
it could be that kmix simply bugs out on the phone and doesn't manage to detect any devices. at any rate, I doubt having two apps running just for the OSD is a very reasonable approach anyway :trollface:

**Comment by mgraesslin** [comment]
after a rebuild of kglobalaccel and kwin the volume buttons work and Plasma 4's OSD is shown if one manually starts kmix (I needed to use konsole to start it. The launcher didn't work).

**Comment by star-buck** [comment]
IMG 135: doesnt work

**Comment by apachelogger** [comment]
uh uh. I have been working on plasma-volume and it should now do the proper plasma OSD (via osdservice). assuming the key mapping is correct this actually should now make it work without kmix

http://mobile.kci.pangea.pub:8080/job/vivid_unstable_plasma-volume-control_bin_armhf/2/

**Comment by star-buck** [comment]
lets ship updated package in next IMG

**Comment by star-buck** [comment]
shipped and initially works
